# Generated by Django 2.2 on 2019-04-12 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("index", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="index.Tag"
            ),
        ),
    ]
