# Generated by Django 2.1.7 on 2019-03-03 02:30

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [("index", "0004_auto_20190215_0140")]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="created_date",
            field=models.DateTimeField(
                db_index=True, default=index.models.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="petitions", to="index.Tag"
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="signed_date",
            field=models.DateTimeField(default=index.models.timezone.now),
        ),
    ]
