# Generated by Django 2.2 on 2019-04-02 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("index", "0005_auto_20190303_0230")]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="petitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="signer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signatures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="User"),
    ]
